# Generated by Django 3.0.4 on 2020-09-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_key', models.CharField(max_length=64, unique=True, verbose_name='配置项键')),
                ('c_value', models.TextField(verbose_name='配置项值')),
                ('remark', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'camus_config',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='项目域名称')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='项目域描述')),
                ('remark', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'project_area',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_area_id', models.BigIntegerField(verbose_name='项目域id')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='项目描述')),
                ('status', models.IntegerField(default=0, verbose_name='项目状态')),
                ('created_person', models.TextField(verbose_name='创建者')),
                ('updated_person', models.TextField(null=True, verbose_name='更新者')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'project_detail',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_detail_id', models.BigIntegerField(verbose_name='项目详情id')),
                ('app_name', models.IntegerField(null=True, verbose_name='涉及应用')),
                ('stage', models.IntegerField(null=True, verbose_name='项目阶段')),
                ('work_time', models.CharField(max_length=64, null=True, verbose_name='工作量')),
                ('outputs', models.CharField(max_length=64, null=True, verbose_name='产出')),
                ('to_measure_time', models.DateField(null=True, verbose_name='提测时间')),
                ('plan_to_prod_time', models.DateField(null=True, verbose_name='计划上线')),
                ('to_prod_time', models.DateField(null=True, verbose_name='实际上线')),
                ('qa_owner', models.CharField(max_length=64, null=True, verbose_name='测试负责人')),
                ('risk_analysis', models.TextField(null=True, verbose_name='风险分析')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('status', models.IntegerField(default=0, verbose_name='进度状态')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'project_progress',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.AddIndex(
            model_name='projectdetail',
            index=models.Index(fields=['name'], name='project_detail_idx'),
        ),
        migrations.AddIndex(
            model_name='projectarea',
            index=models.Index(fields=['name'], name='project_area_idx'),
        ),
        migrations.AddIndex(
            model_name='camusconfig',
            index=models.Index(fields=['c_key'], name='camus_config_idx'),
        ),
    ]
