# Generated by Django 3.0.4 on 2020-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.BigIntegerField(verbose_name='项目ID')),
                ('case_title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('case_detail', models.TextField(null=True, verbose_name='用例详情')),
                ('case_priority', models.CharField(blank=True, choices=[('URGENT', 'P0'), ('HIGH', 'P1'), ('MEDIUM', 'P2'), ('LOW', 'P3')], max_length=10, verbose_name='用例优先级')),
                ('case_status', models.CharField(choices=[('NO_EXECUTE', '未执行'), ('PASS', '通过'), ('FAILED', '失败'), ('BLOCK', '阻塞'), ('HAND_UP', '挂起')], default='NO_EXECUTE', max_length=10, verbose_name='用例状态')),
                ('case_bug', models.BooleanField(default=False)),
                ('created_person', models.TextField(verbose_name='创建者')),
                ('updated_person', models.TextField(null=True, verbose_name='更新者')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'case_base',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.BigIntegerField(verbose_name='项目ID')),
                ('excel_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('excel_alias_name', models.TextField(verbose_name='文件别名')),
                ('upload_person', models.TextField(verbose_name='创建者')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'case_file',
                'ordering': ['gmt_created'],
            },
        ),
        migrations.AddIndex(
            model_name='casefile',
            index=models.Index(fields=['excel_name'], name='case_file_idx'),
        ),
        migrations.AddIndex(
            model_name='casebase',
            index=models.Index(fields=['case_title'], name='case_base_idx'),
        ),
    ]
